name: Examine the Node.js Bindings
on:
  push:
    branches:
      - develop
      - production
    paths:
      - ".github/workflows/examine-nodejs-bindings.yml"
      - ".github/actions/**"
      - "client/bindings/nodejs/**"
      # Watch the Rust core too
      - "client/src/**"
      - "client/Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches:
      - develop
      - production
    paths:
      - ".github/workflows/examine-nodejs-bindings.yml"
      - ".github/actions/**"
      - "client/bindings/nodejs/**"
      # Watch the Rust core too
      - "client/src/**"
      - "client/Cargo.toml"
      - "Cargo.lock"
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    if: ${{ ! github.event.schedule }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: ["14", "16", "18"]

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v3

      - name: Set Up Nightly Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          cache: true
          cache-root: client/bindings/nodejs/
          cache-job-id: ${{ github.workflow }}-${{ github.job }}-${{ matrix.os }}-${{ matrix.node }}
          cache-hash: ${{ hashFiles('.github/workflows/examine-nodejs-bindings.yml') }}

      - name: Set Up Node.js ${{ matrix.node }} and Yarn Cache
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: client/bindings/nodejs/yarn.lock

      # This step is required for bindgen to work on Windows.
      - name: Set Up Clang/LLVM (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: ./.github/actions/setup-clang

      - name: Install Required Dependencies (Ubuntu)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Run Yarn Install
        working-directory: client/bindings/nodejs/
        run: yarn install

      - name: Run Yarn Rebuild
        working-directory: client/bindings/nodejs/
        run: yarn rebuild

      - name: Run Yarn Test
        working-directory: client/bindings/nodejs/
        run: yarn test

  lint:
    name: Lint
    if: ${{ ! github.event.schedule }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v3

      - name: Set Up Beta Clippy
        uses: ./.github/actions/setup-rust
        with:
          toolchain: beta
          components: clippy
          cache: true
          cache-root: client/bindings/nodejs/
          cache-job-id: ${{ github.workflow }}-${{ github.job }}
          cache-hash: ${{ hashFiles('.github/workflows/examine-nodejs-bindings.yml') }}

      - name: Install Required Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Run Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path client/bindings/nodejs/Cargo.toml --all-features --all-targets -- --deny warnings
          name: Clippy Results for the Node.js Bindings

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: client/bindings/nodejs/yarn.lock
          node-version: 14.x

      - name: Install Dependencies
        working-directory: client/bindings/nodejs/
        run: yarn

      - name: Lint
        working-directory: client/bindings/nodejs/
        run: yarn lint

  check-unused-deps:
    name: Check Unused Dependencies
    if: ${{ ! github.event.schedule }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v3

      - name: Install Cargo-udeps with Nightly Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          cache: true
          install: cargo-udeps
          cache-root: client/bindings/nodejs/
          cache-job-id: ${{ github.workflow }}-${{ github.job }}
          cache-hash: ${{ hashFiles('.github/workflows/examine-nodejs-bindings.yml') }}

      - name: Install Required Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Run Cargo Udeps
        uses: actions-rs/cargo@v1
        with:
          command: udeps
          args: --manifest-path client/bindings/nodejs/Cargo.toml --all-targets --all-features

      # TODO: Check yarn too

  check-format:
    name: Check Format
    if: ${{ ! github.event.schedule }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v3

      - name: Set Up Nightly Rustfmt
        uses: ./.github/actions/setup-rust
        with:
          toolchain: nightly
          components: rustfmt
          cache: false

      - name: Install cargo-license-template
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --force cargo-license-template

      - name: Install Required Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Run Cargo Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path client/bindings/nodejs/Cargo.toml --all -- --check

      - name: Run cargo-license-template
        uses: actions-rs/cargo@v1
        with:
          command: license-template
          args: --template .license_template

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: client/bindings/nodejs/yarn.lock
          node-version: 14.x

      - name: Install Dependencies
        working-directory: client/bindings/nodejs/
        run: yarn

      - name: Format
        working-directory: client/bindings/nodejs/
        run: yarn format-check
